# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TableInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableInterfaceForm(object):
    def setupUi(self, TableInterfaceForm):
        TableInterfaceForm.setObjectName("TableInterfaceForm")
        TableInterfaceForm.resize(1002, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableInterfaceForm.sizePolicy().hasHeightForWidth())
        TableInterfaceForm.setSizePolicy(sizePolicy)
        TableInterfaceForm.setMinimumSize(QtCore.QSize(900, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(TableInterfaceForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_view = TableView(TableInterfaceForm)
        self.table_view.setMinimumSize(QtCore.QSize(900, 0))
        self.table_view.setObjectName("table_view")
        self.verticalLayout.addWidget(self.table_view)

        self.retranslateUi(TableInterfaceForm)
        QtCore.QMetaObject.connectSlotsByName(TableInterfaceForm)

    def retranslateUi(self, TableInterfaceForm):
        _translate = QtCore.QCoreApplication.translate
        TableInterfaceForm.setWindowTitle(_translate("TableInterfaceForm", "Form"))
from qfluentwidgets import TableView
